skip_non_accepted: true
my_emails:
  - cboudjna@redhat.com
event_organizers_icon:
  "(pbhattac|gurose|nkakkar|rbehera|vdemeest|kbaig|pchandra|ssadeghi|hshinde|nikthoma|pthangad|yhontyk|varadhya|pgarg|pradkuma|sashture|sthaha|gmontero|ppitonak)@redhat.com": "ğŸˆ"
title_match_icon:
  ".*Tekton.*Working Group.*": "ğŸ˜¼"
  "^Tekton.*Office Hours.*": "ğŸ˜¼"
  "^Tekton.*OpenShift.*Pipelines.*Grooming": "ğŸ‘·"
  "^Tekton Workflows/PipelineAsCode WG": "ğŸ’¡"
  ".*Sprint Review.*": "ğŸ¦‚"
  "^WHOTT.*": "ğŸ¤©"
restrict_to_calendar:
  - Work
  - Personal
default_icon: "â†ª"
title_max_char: 30
change_icon_minutes: 5
refresh_interval: 60
strip_title_emojis: true
